# Generated by Django 3.0.7 on 2023-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('apiKey', models.CharField(max_length=255)),
                ('secretKey', models.CharField(max_length=255)),
            ],
        ),
    ]
